name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  semver:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.semver.outputs.next }}
    steps:
      - name: Set up SemVer
        uses: ietf-tools/semver-action@v1.10.2
        id: semver
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          noVersionBumpBehavior: silent
          patchList: '["build", "fix", "bugfix", "perf", "refactor"]'

      - name: Create tag
        run: |
          git tag ${{ needs.semver.outputs.version }}
          git push origin ${{ needs.semver.outputs.version}}

  build:
    runs-on: ubuntu-24.04
    needs: semver
    # if: ${{ needs.semver.outputs.version != '' }}
    strategy:
      matrix:
        architecture: [linux/amd64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Extract Docker metadata
        uses: docker/metadata-action@v5.7.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{raw}},value=${{ needs.semver.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: ${{ matrix.architecture }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true
          # push: true
        env:
          SOURCE_DATE_EPOCH: 0